files:
  version: release.version
bump:
  enabled: true
  base-branch: main
  label: autobump
release:
  full-release: true
  publish: false

deploy:
  auto-dev: false

terraform:
  enabled: true
  working-directory: terraform
