files:
  version: release.version
qodana:
  enabled: false
bump:
  enabled: true
  base-branch: main
  label: autobump
release:
  full-release: true
  publish: false
terraform:
  enabled: true
  working-directory: terraform
