FROM python:3.14-slim@sha256:cea0e6040540fb2b965b6e7fb5ffa00871e632eef63719f0ea54bca189ce14a6

WORKDIR /app

RUN pip install --no-cache-dir \
    "boto3==1.43.46" \
    "requests==2.34.2" \
    "pytest==9.1.1" \
    "pytest-timeout==2.4.0" \
    "tenacity==9.1.4"

COPY tests/ /app/tests/
COPY run-e2e-tests.py /app/

ENTRYPOINT ["python", "run-e2e-tests.py"]
