FROM python:3.14-slim@sha256:b877e50bd90de10af8d82c57a022fc2e0dc731c5320d762a27986facfc3355c1

WORKDIR /app

COPY requirements.lock /app/requirements.lock
RUN pip install --no-cache-dir --require-hashes -r /app/requirements.lock

COPY tests/ /app/tests/
COPY run-e2e-tests.py /app/

ENTRYPOINT ["python", "run-e2e-tests.py"]
